# Generated by Django 3.2.8 on 2021-12-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
