# Generated by Django 3.2.8 on 2021-12-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20211202_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='noteName',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
