# Generated by Django 3.2.8 on 2021-12-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_notename'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.CharField(default='from notes.models import Notes', max_length=50, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
